use ripetizioni;

insert into materia (nome) values ('Modulo 100');
insert into materia (nome) values ('Modulo 101');
insert into materia (nome) values ('Modulo 104');
insert into materia (nome) values ('Modulo 105');
insert into materia (nome) values ('Modulo 114');
insert into materia (nome) values ('Modulo 117');
insert into materia (nome) values ('Modulo 121');
insert into materia (nome) values ('Modulo 122');
insert into materia (nome) values ('Modulo 123');
insert into materia (nome) values ('Modulo 127');
insert into materia (nome) values ('Modulo 129');
insert into materia (nome) values ('Modulo 133');
insert into materia (nome) values ('Modulo 141');
insert into materia (nome) values ('Modulo 143');
insert into materia (nome) values ('Modulo 146');
insert into materia (nome) values ('Modulo 151');
insert into materia (nome) values ('Modulo 153');
insert into materia (nome) values ('Modulo 159');
insert into materia (nome) values ('Modulo 184');
insert into materia (nome) values ('Modulo 214');
insert into materia (nome) values ('Modulo 223');
insert into materia (nome) values ('Modulo 226A');
insert into materia (nome) values ('Modulo 226B');
insert into materia (nome) values ('Modulo 239');
insert into materia (nome) values ('Modulo 300');
insert into materia (nome) values ('Modulo 302');
insert into materia (nome) values ('Modulo 304');
insert into materia (nome) values ('Modulo 305');
insert into materia (nome) values ('Modulo 306');
insert into materia (nome) values ('Modulo 307');
insert into materia (nome) values ('Modulo 318');
insert into materia (nome) values ('Modulo 335');
insert into materia (nome) values ('Modulo 340');
insert into materia (nome) values ('Modulo 403');
insert into materia (nome) values ('Modulo 404');
insert into materia (nome) values ('Modulo 431');
insert into materia (nome) values ('Economia e diritto');
insert into materia (nome) values ('Educazione fisica');
insert into materia (nome) values ('Etica professionale');
insert into materia (nome) values ('Inglese MP');
insert into materia (nome) values ('Italiano MP');
insert into materia (nome) values ('Laboratorio di consolidamento');
insert into materia (nome) values ('Laboratorio elettronica 1');
insert into materia (nome) values ('Laboratorio elettronica 2');
insert into materia (nome) values ('Laboratorio robotica 1');
insert into materia (nome) values ('Matematica Fondamentale');
insert into materia (nome) values ('Materie complementari');
insert into materia (nome) values ('Portfolio delle competenze');
insert into materia (nome) values ('Progetti individuali');
insert into materia (nome) values ('Scienze naturali Chimica');
insert into materia (nome) values ('Scienze naturali Fisica');
insert into materia (nome) values ('Storia e politica');
insert into materia (nome) values ('Tedesco MP');